FROM node:8-slim

# Install latest chrome dev package.
# Note: this installs the necessary libs to make the bundled version of Chromium that Pupppeteer installs, work.
RUN apt-get update && apt-get install -y wget vim --no-install-recommends \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-unstable libgconf-2-4 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get purge --auto-remove -y curl \
    && rm -rf /src/*.deb

# Copy the application files.
WORKDIR /usr/tdl-reports

# Install dependencies
COPY package.json /usr/tdl-reports/
ENV NODE_ENV dev
RUN npm install

# Compile and bundle.
COPY gulpfile.js  /usr/tdl-reports/
COPY dist         /usr/tdl-reports/dist
COPY src          /usr/tdl-reports/src
RUN /usr/tdl-reports/node_modules/.bin/gulp

# Mount volume
VOLUME /usr/tdl-reports/tests_output

# Run tests.
COPY tests        /usr/tdl-reports/tests
CMD ["npm", "test"]
